# Generated by Django 6.0.6 on 2026-07-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=1, help_text='Weight in kilograms', max_digits=6)),
                ('record_date', models.DateField(auto_now_add=True, help_text='Date of weight measurement')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='cattle.cattle')),
            ],
            options={
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-record_date'],
                'unique_together': {('cattle', 'record_date')},
            },
        ),
    ]
