# Generated by Django 6.0.6 on 2026-07-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sire_external', models.CharField(blank=True, help_text="Description of sire if not in system (e.g., 'AI Bull #123')", max_length=100, null=True)),
                ('breeding_method', models.CharField(choices=[('NATURAL', 'Natural Mating'), ('AI', 'Artificial Insemination')], default='NATURAL', max_length=20)),
                ('service_date', models.DateField(help_text='Date of breeding/insemination')),
                ('pregnancy_status', models.CharField(choices=[('SUSPECTED', 'Suspected'), ('CONFIRMED', 'Confirmed'), ('ABORTED', 'Aborted'), ('CALVED', 'Calved'), ('NOT_PREGNANT', 'Not Pregnant')], default='SUSPECTED', max_length=20)),
                ('confirmation_date', models.DateField(blank=True, help_text='Date pregnancy was confirmed', null=True)),
                ('expected_calving_date', models.DateField(blank=True, help_text='Expected date of calving (280 days after service)', null=True)),
                ('actual_calving_date', models.DateField(blank=True, help_text='Actual date of calving (filled when calving occurs)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(help_text='The female animal that is/was pregnant', limit_choices_to={'sex': 'Female'}, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='cattle.cattle')),
                ('sire', models.ForeignKey(blank=True, help_text='The male animal that sired the pregnancy (if known)', limit_choices_to={'sex': 'Male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_pregnancies', to='cattle.cattle')),
            ],
            options={
                'verbose_name_plural': 'Pregnancy Records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField(help_text='Date of birth')),
                ('calving_outcome', models.CharField(choices=[('LIVE', 'Live Birth'), ('STILLBIRTH', 'Stillbirth'), ('MISCARRIAGE', 'Miscarriage')], default='LIVE', max_length=20)),
                ('number_of_calves', models.PositiveSmallIntegerField(default=1, help_text='Number of calves born')),
                ('complications', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('calf', models.OneToOneField(help_text='The calf that was born', on_delete=django.db.models.deletion.CASCADE, related_name='birth_record', to='cattle.cattle')),
                ('mother', models.ForeignKey(help_text='The mother that gave birth', limit_choices_to={'sex': 'Female'}, on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='cattle.cattle')),
                ('pregnancy', models.ForeignKey(blank=True, help_text='Link to the pregnancy record (if tracked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calving', to='breeding.pregnancyrecord')),
            ],
            options={
                'verbose_name_plural': 'Calving Records',
                'ordering': ['-calving_date'],
            },
        ),
    ]
