# Generated by Django 6.0.6 on 2026-07-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_tag', models.CharField(help_text='Official Government Tag number', max_length=20, unique=True)),
                ('ear_tag', models.CharField(help_text='Unique identification tag number bought for animal', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for the animal', max_length=100, null=True)),
                ('breed', models.CharField(choices=[('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Tswana', 'Tswana'), ('Nguni', 'Nguni'), ('Crossbreed', 'Crossbreed'), ('Other', 'Other')], max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Red', 'Red'), ('Roan', 'Roan'), ('Grey', 'Grey'), ('Spotted', 'Spotted'), ('Other', 'Other')], max_length=20, null=True)),
                ('current_status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Missing', 'Missing'), ('Deceased', 'Deceased')], default='Active', max_length=20)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Injury', 'Injury'), ('Under Treatment', 'Under Treatment'), ('Quarantined', 'Qurantined')], default='Healthy', max_length=20)),
                ('location', models.CharField(default='Kraal 1', help_text='Current kraal', max_length=100)),
                ('mother_gov_tag', models.CharField(blank=True, help_text='Government tag of mother', max_length=20, null=True)),
                ('father_gov_tag', models.CharField(blank=True, help_text='Government tag of father', max_length=20, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in BWP', max_digits=12, null=True)),
                ('source_supplier', models.CharField(blank=True, help_text='Where the animal was purchased from', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload a photo of the animal', null=True, upload_to='cattle_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cattle',
                'ordering': ['gov_tag'],
            },
        ),
        migrations.CreateModel(
            name='CattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('CALVING', 'Calving'), ('VACCINATION', 'Vaccination'), ('HEALTH_CHECK', 'Health Check'), ('SOLD', 'Sold'), ('PURCHASED', 'Purchased'), ('MISSING_REPORTED', 'Missing Reported'), ('FOUND', 'Found')], max_length=50)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cattle.cattle')),
            ],
            options={
                'verbose_name_plural': 'Cattle Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
