# Generated by Django 6.0.6 on 2026-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='colour',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Red', 'Red'), ('Roan', 'Roan'), ('Grey', 'Grey'), ('Spotted', 'Spotted'), ('Tshwaana', 'Tshwaana'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
