# Generated by Django 6.0.6 on 2026-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_alter_cattle_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.CharField(choices=[('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Charalois', 'Charalois'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Tswana', 'Tswana'), ('Nguni', 'Nguni'), ('Crossbreed', 'Crossbreed'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='colour',
            field=models.CharField(blank=True, choices=[('Tshumu', 'Tshumu'), ('Tsweu', 'Tsweu'), ('Naana', 'Naana'), ('Nala', 'Nala'), ('Tshumo e Bothiba', 'Tshumo e bothiba'), ('Tshumo e Bosetha', 'Tshumo e bosetha'), ('Khonou', 'Khonou'), ('Khunwana', 'Khunwana'), ('Tshwaana', 'Tshwaana'), ('Tubanaa', 'Tubana'), ('Tshunyana', 'Tshunyana'), ('Tshunyana e botihabana', 'Tshunyana e botihabana'), ('Tshetiha', 'Tshetiha'), ('Kgweba', 'Kgweba'), ('Tubana', 'Tubana'), ('Champana', 'Champana'), ('Tihaba', 'Tihaba'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
