# Generated by Django 6.0.6 on 2026-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_alter_cattle_breed_alter_cattle_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='colour',
            field=models.CharField(blank=True, choices=[('Tshumu', 'Tshumu'), ('Tsweu', 'Tsweu'), ('Naana', 'Naana'), ('Nala', 'Nala'), ('Tshumo e Bothaba', 'Tshumo e bothaba'), ('Tshumo e Bosetha', 'Tshumo e bosetha'), ('Khonou', 'Khonou'), ('Khunwana', 'Khunwana'), ('Tshwaana', 'Tshwaana'), ('Tubanaa', 'Tubana'), ('Tshunyana', 'Tshunyana'), ('Tshunyana e botlhabana', 'Tshunyana e botlhabana'), ('Tshetlha', 'Tshetlha'), ('Kgweba', 'Kgweba'), ('Tubana', 'Tubana'), ('Champana', 'Champana'), ('Tlhaba', 'Tlhaba'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
