# Generated by Django 6.0.6 on 2026-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_alter_cattle_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='ear_tag',
            field=models.CharField(help_text='Unique identification tag number bought for animal', max_length=20, null=True, unique=True),
        ),
    ]
